/*
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DomainDslStandaloneSetup extends DomainDslStandaloneSetupGenerated {

	def static void doSetup() {
		new DomainDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
