/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.domainDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends Type
{
} // DataType
