/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.domainDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Feature#isMany <em>Many</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Feature#getName <em>Name</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Feature#getType <em>Type</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Feature#getDefaultVal <em>Default Val</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Feature#getValdiators <em>Valdiators</em>}</li>
 * </ul>
 *
 * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
  /**
   * Returns the value of the '<em><b>Many</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Many</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Many</em>' attribute.
   * @see #setMany(boolean)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature_Many()
   * @model
   * @generated
   */
  boolean isMany();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Feature#isMany <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Many</em>' attribute.
   * @see #isMany()
   * @generated
   */
  void setMany(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Feature#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(Type)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature_Type()
   * @model
   * @generated
   */
  Type getType();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Feature#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(Type value);

  /**
   * Returns the value of the '<em><b>Default Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Default Val</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Val</em>' attribute.
   * @see #setDefaultVal(String)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature_DefaultVal()
   * @model
   * @generated
   */
  String getDefaultVal();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Feature#getDefaultVal <em>Default Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Val</em>' attribute.
   * @see #getDefaultVal()
   * @generated
   */
  void setDefaultVal(String value);

  /**
   * Returns the value of the '<em><b>Valdiators</b></em>' containment reference list.
   * The list contents are of type {@link org.wcmda.domaindsl.domainDsl.Validator}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Valdiators</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Valdiators</em>' containment reference list.
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getFeature_Valdiators()
   * @model containment="true"
   * @generated
   */
  EList<Validator> getValdiators();

} // Feature
