/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.domainDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Validator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Validator#getName <em>Name</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Validator#getValue <em>Value</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.Validator#getSvalue <em>Svalue</em>}</li>
 * </ul>
 *
 * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getValidator()
 * @model
 * @generated
 */
public interface Validator extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getValidator_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Validator#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getValidator_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Validator#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Svalue</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Svalue</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Svalue</em>' attribute.
   * @see #setSvalue(String)
   * @see org.wcmda.domaindsl.domainDsl.DomainDslPackage#getValidator_Svalue()
   * @model
   * @generated
   */
  String getSvalue();

  /**
   * Sets the value of the '{@link org.wcmda.domaindsl.domainDsl.Validator#getSvalue <em>Svalue</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Svalue</em>' attribute.
   * @see #getSvalue()
   * @generated
   */
  void setSvalue(String value);

} // Validator
