/*
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainDslScopeProvider extends DelegatingScopeProvider {
}
