/*
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.wcmda.domaindsl.services.DomainDslGrammarAccess;

@SuppressWarnings("all")
public class DomainDslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DomainDslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_EType_CurrencyKeyword_4_or_DateKeyword_5_or_DateTimeKeyword_6_or_DoubleKeyword_3_or_LongKeyword_2_or_StringKeyword_1_or_TimeStampKeyword_7;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DomainDslGrammarAccess) access;
		match_EType_CurrencyKeyword_4_or_DateKeyword_5_or_DateTimeKeyword_6_or_DoubleKeyword_3_or_LongKeyword_2_or_StringKeyword_1_or_TimeStampKeyword_7 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getETypeAccess().getCurrencyKeyword_4()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getDateKeyword_5()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getDateTimeKeyword_6()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getDoubleKeyword_3()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getLongKeyword_2()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getStringKeyword_1()), new TokenAlias(false, false, grammarAccess.getETypeAccess().getTimeStampKeyword_7()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_EType_CurrencyKeyword_4_or_DateKeyword_5_or_DateTimeKeyword_6_or_DoubleKeyword_3_or_LongKeyword_2_or_StringKeyword_1_or_TimeStampKeyword_7.equals(syntax))
				emit_EType_CurrencyKeyword_4_or_DateKeyword_5_or_DateTimeKeyword_6_or_DoubleKeyword_3_or_LongKeyword_2_or_StringKeyword_1_or_TimeStampKeyword_7(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     (
	  *         'String' | 
	  *         'Long' | 
	  *         'Double' | 
	  *         'Currency' | 
	  *         'Date' | 
	  *         'DateTime' | 
	  *         'TimeStamp'
	  *     )
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) (rule start)
	 */
	protected void emit_EType_CurrencyKeyword_4_or_DateKeyword_5_or_DateTimeKeyword_6_or_DoubleKeyword_3_or_LongKeyword_2_or_StringKeyword_1_or_TimeStampKeyword_7(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
