/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.validation;

import org.wcmda.domaindsl.validation.AbstractDomainDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DomainDslValidator extends AbstractDomainDslValidator {
}
