/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl;

import org.wcmda.domaindsl.DomainDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainDslStandaloneSetup extends DomainDslStandaloneSetupGenerated {
  public static void doSetup() {
    new DomainDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
