/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl;

import org.wcmda.domaindsl.AbstractDomainDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DomainDslRuntimeModule extends AbstractDomainDslRuntimeModule {
}
