/**
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.domainDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.wcmda.domaindsl.domainDsl.DomainDslPackage;
import org.wcmda.domaindsl.domainDsl.Feature;
import org.wcmda.domaindsl.domainDsl.Type;
import org.wcmda.domaindsl.domainDsl.Validator;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.impl.FeatureImpl#isMany <em>Many</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.impl.FeatureImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.impl.FeatureImpl#getType <em>Type</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.impl.FeatureImpl#getDefaultVal <em>Default Val</em>}</li>
 *   <li>{@link org.wcmda.domaindsl.domainDsl.impl.FeatureImpl#getValdiators <em>Valdiators</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FeatureImpl extends MinimalEObjectImpl.Container implements Feature
{
  /**
   * The default value of the '{@link #isMany() <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMany()
   * @generated
   * @ordered
   */
  protected static final boolean MANY_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isMany() <em>Many</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isMany()
   * @generated
   * @ordered
   */
  protected boolean many = MANY_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected Type type;

  /**
   * The default value of the '{@link #getDefaultVal() <em>Default Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultVal()
   * @generated
   * @ordered
   */
  protected static final String DEFAULT_VAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getDefaultVal() <em>Default Val</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDefaultVal()
   * @generated
   * @ordered
   */
  protected String defaultVal = DEFAULT_VAL_EDEFAULT;

  /**
   * The cached value of the '{@link #getValdiators() <em>Valdiators</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValdiators()
   * @generated
   * @ordered
   */
  protected EList<Validator> valdiators;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FeatureImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainDslPackage.Literals.FEATURE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public boolean isMany()
  {
    return many;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setMany(boolean newMany)
  {
    boolean oldMany = many;
    many = newMany;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainDslPackage.FEATURE__MANY, oldMany, many));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainDslPackage.FEATURE__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type getType()
  {
    if (type != null && type.eIsProxy())
    {
      InternalEObject oldType = (InternalEObject)type;
      type = (Type)eResolveProxy(oldType);
      if (type != oldType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, DomainDslPackage.FEATURE__TYPE, oldType, type));
      }
    }
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Type basicGetType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setType(Type newType)
  {
    Type oldType = type;
    type = newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainDslPackage.FEATURE__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getDefaultVal()
  {
    return defaultVal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDefaultVal(String newDefaultVal)
  {
    String oldDefaultVal = defaultVal;
    defaultVal = newDefaultVal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DomainDslPackage.FEATURE__DEFAULT_VAL, oldDefaultVal, defaultVal));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Validator> getValdiators()
  {
    if (valdiators == null)
    {
      valdiators = new EObjectContainmentEList<Validator>(Validator.class, this, DomainDslPackage.FEATURE__VALDIATORS);
    }
    return valdiators;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DomainDslPackage.FEATURE__VALDIATORS:
        return ((InternalEList<?>)getValdiators()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainDslPackage.FEATURE__MANY:
        return isMany();
      case DomainDslPackage.FEATURE__NAME:
        return getName();
      case DomainDslPackage.FEATURE__TYPE:
        if (resolve) return getType();
        return basicGetType();
      case DomainDslPackage.FEATURE__DEFAULT_VAL:
        return getDefaultVal();
      case DomainDslPackage.FEATURE__VALDIATORS:
        return getValdiators();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainDslPackage.FEATURE__MANY:
        setMany((Boolean)newValue);
        return;
      case DomainDslPackage.FEATURE__NAME:
        setName((String)newValue);
        return;
      case DomainDslPackage.FEATURE__TYPE:
        setType((Type)newValue);
        return;
      case DomainDslPackage.FEATURE__DEFAULT_VAL:
        setDefaultVal((String)newValue);
        return;
      case DomainDslPackage.FEATURE__VALDIATORS:
        getValdiators().clear();
        getValdiators().addAll((Collection<? extends Validator>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainDslPackage.FEATURE__MANY:
        setMany(MANY_EDEFAULT);
        return;
      case DomainDslPackage.FEATURE__NAME:
        setName(NAME_EDEFAULT);
        return;
      case DomainDslPackage.FEATURE__TYPE:
        setType((Type)null);
        return;
      case DomainDslPackage.FEATURE__DEFAULT_VAL:
        setDefaultVal(DEFAULT_VAL_EDEFAULT);
        return;
      case DomainDslPackage.FEATURE__VALDIATORS:
        getValdiators().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainDslPackage.FEATURE__MANY:
        return many != MANY_EDEFAULT;
      case DomainDslPackage.FEATURE__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case DomainDslPackage.FEATURE__TYPE:
        return type != null;
      case DomainDslPackage.FEATURE__DEFAULT_VAL:
        return DEFAULT_VAL_EDEFAULT == null ? defaultVal != null : !DEFAULT_VAL_EDEFAULT.equals(defaultVal);
      case DomainDslPackage.FEATURE__VALDIATORS:
        return valdiators != null && !valdiators.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (many: ");
    result.append(many);
    result.append(", name: ");
    result.append(name);
    result.append(", defaultVal: ");
    result.append(defaultVal);
    result.append(')');
    return result.toString();
  }

} //FeatureImpl
