/*
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.wcmda.domaindsl.parser.antlr.internal.InternalDomainDslParser;
import org.wcmda.domaindsl.services.DomainDslGrammarAccess;

public class DomainDslParser extends AbstractAntlrParser {

	@Inject
	private DomainDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDomainDslParser createParser(XtextTokenStream stream) {
		return new InternalDomainDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Domainmodel";
	}

	public DomainDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DomainDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
