/*
 * generated by Xtext 2.12.0
 */
package org.wcmda.domaindsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DomainDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/wcmda/domaindsl/parser/antlr/internal/InternalDomainDsl.tokens");
	}
}
